
import AboutMe from "@/components/Aboutme";
import Contact from "@/components/Contact";
import Header from "@/components/header";
import Home from "@/components/Home";
import { Knowledge } from "@/components/Knowledge";
import Projects from "@/components/Projects";
import { Metadata } from "../../node_modules/next/types";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="">
      <body className="bg-gray-500/40">
        <main>
          <Header />
          <Home/>
          <AboutMe />
          <Projects />
          <Knowledge />
          <Contact />
          {children}
        </main>
      </body>
    </html>
  );
}
